#!/usr/bin/env ruby

blacklist = []
remappings = {}

File.open("perseus-blacklist") do |f|
  f.each_line do |l|
    l.chomp!
    l.sub!(/\#.*$/, '')
    l.split(/\s+/).each do |lm|
      if lm[/^(.*)>(.*)$/]
        # A remapping
        remappings[$1] = $2
      else
        # A blacklisting
        blacklist << lm
      end
    end
  end
end

blacklist.uniq!

ARGF.each_line do |l|
  language, lemma, variant, *rest = l.split(',')
  key = variant != '' ? [lemma, variant].join(':') : lemma
  unless blacklist.include?(key)
    if n = remappings[key]
      lemma, variant = n.split(':')
      puts ([language, lemma, variant] + rest).join(',')
    else
      puts l
    end
  end
end
