new:
  summary: new
kind:
  summary: kind
acc_gen:
  summary: acc-gen
acc_sit:
  summary: acc-sit
acc_inf:
  summary: acc-inf
old:
  summary: old
old_inact:
  summary: old-inact
no_info_status:
  summary: annotatable (undecided)
info_unannotatable:
  summary: unannotatable
quant:
  summary: quantifier restriction
non_spec:
  summary: non-specific
non_spec_inf:
  summary: inferred from non-specific
non_spec_old:
  summary: non-specific old
