:mood:
  i:
    abbreviated_summary: ind.
    summary: indicative
  s:
    abbreviated_summary: subj.
    summary: subjunctive
  m:
    abbreviated_summary: imp.
    summary: imperative
  o:
    abbreviated_summary: opt.
    summary: optative
  n:
    abbreviated_summary: inf.
    summary: infinitive
  p:
    abbreviated_summary: part.
    summary: participle
  d:
    abbreviated_summary: gerund
    summary: gerund
  g:
    abbreviated_summary: gerundive
    summary: gerundive
  u:
    abbreviated_summary: sup.
    summary: supine
  x:
    abbreviated_summary: unc. mood
    summary: uncertain mood
  y:
    abbreviated_summary: unspec.fin.
    summary: finiteness unspecified
  e:
    abbreviated_summary: ind./subj.
    summary: indicative or subjunctive
  f:
    abbreviated_summary: ind./imp.
    summary: indicative or imperative
  h:
    abbreviated_summary: subj./imp.
    summary: subjunctive or imperative
  t:
    abbreviated_summary: finite
    summary: finite
:inflection:
  n:
    abbreviated_summary: non-infl.
    summary: non-inflecting
  i:
    abbreviated_summary: infl.
    summary: inflecting
:number:
  s:
    abbreviated_summary: sg.
    summary: singular
  d:
    abbreviated_summary: du.
    summary: dual
  p:
    abbreviated_summary: pl.
    summary: plural
  x:
    abbreviated_summary: unc. nb.
    summary: uncertain number
:voice:
  a:
    abbreviated_summary: act.
    summary: active
  m:
    abbreviated_summary: mid.
    summary: middle
  p:
    abbreviated_summary: pass.
    summary: passive
  e:
    abbreviated_summary: mid./pass.
    summary: middle or passive
  x:
    abbreviated_summary: unspec.
    summary: unspecified
:case:
  n:
    abbreviated_summary: nom.
    summary: nominative
  a:
    abbreviated_summary: acc.
    summary: accusative
  o:
    abbreviated_summary: obl.
    summary: oblique
  g:
    abbreviated_summary: gen.
    summary: genitive
  c:
    abbreviated_summary: gen./dat.
    summary: genitive or dative
  e:
    abbreviated_summary: acc./dat.
    summary: accusative or dative
  d:
    abbreviated_summary: dat.
    summary: dative
  b:
    abbreviated_summary: abl.
    summary: ablative
  i:
    abbreviated_summary: ins.
    summary: instrumental
  l:
    abbreviated_summary: loc.
    summary: locative
  v:
    abbreviated_summary: voc.
    summary: vocative
  x:
    abbreviated_summary: unc. case
    summary: uncertain case
  z:
    abbreviated_summary: no case
    summary: no case
:degree:
  p:
    abbreviated_summary: pos.
    summary: positive
  c:
    abbreviated_summary: comp.
    summary: comparative
  s:
    abbreviated_summary: supl.
    summary: superlative
  x:
    abbreviated_summary: unc. deg.
    summary: uncertain degree
  z:
    abbreviated_summary: no degree
    summary: no degree
:gender:
  m:
    abbreviated_summary: m.
    summary: masculine
  f:
    abbreviated_summary: f.
    summary: feminine
  n:
    abbreviated_summary: n.
    summary: neuter
  p:
    abbreviated_summary: m./f.
    summary: masculine or feminine
  o:
    abbreviated_summary: m./n.
    summary: masculine or neuter
  r:
    abbreviated_summary: f./n.
    summary: feminine or neuter
  q:
    abbreviated_summary: m./f./n.
    summary: masculine, feminine or neuter
  x:
    abbreviated_summary: unc. gender
    summary: uncertain gender
:strength:
  w:
    abbreviated_summary: weak
    summary: weak
  s:
    abbreviated_summary: strong
    summary: strong
  t:
    abbreviated_summary: weak/strong
    summary: weak or strong
:person:
  "1":
    abbreviated_summary: 1st p.
    summary: first person
  "2":
    abbreviated_summary: 2nd p.
    summary: second person
  "3":
    abbreviated_summary: 3rd p.
    summary: third person
  x:
    abbreviated_summary: unc. p.
    summary: uncertain person
:tense:
  p:
    abbreviated_summary: pres.
    summary: present
  i:
    abbreviated_summary: imperf.
    summary: imperfect
  r:
    abbreviated_summary: perf.
    summary: perfect
  s:
    abbreviated_summary: result.
    summary: resultative
  a:
    abbreviated_summary: aor.
    summary: aorist
  u:
    abbreviated_summary: past
    summary: past
  l:
    abbreviated_summary: ppf.
    summary: pluperfect
  f:
    abbreviated_summary: fut.
    summary: future
  t:
    abbreviated_summary: fut. perf.
    summary: future perfect
  x:
    abbreviated_summary: unc. tense
    summary: uncertain tense
