> glagolati
<INFINITIVE><VERB>glagolati
> kričati
<INFINITIVE><VERB>kričati
> rinǫti
<INFINITIVE><VERB>rinǫti
> rinǫ
<1><INDICATIVE><PRESENT><SIN><VERB>rinǫti
> rinǫtŭ
<3><INDICATIVE><PLU><PRESENT><VERB>rinǫti
> mĭněti
<INFINITIVE><VERB>mĭněti
> mĭniši
<2><INDICATIVE><PRESENT><SIN><VERB>mĭněti
> mĭnętŭ
<3><INDICATIVE><PLU><PRESENT><VERB>mĭněti
> moliši
<2><INDICATIVE><PRESENT><SIN><VERB>moliti
> nositi
<INFINITIVE><VERB>nositi
> nosętŭ
<3><INDICATIVE><PLU><PRESENT><VERB>nositi
